### ISSUE TITLE
A question about the cdvae

### ISSUE THREAD

**Issue by szy120320** [txie-93/cdvae#36]
Excuse me, I'm a first-year graduate student. My programming ability is limited. So I have a question. 
1. I want to know what the `MODEL_PATH `is. I tried many paths, but none of them worked. this is the hint: 
 ```
hydra.errors.MissingConfigException: Primary config directory not found.
Check that the config directory '\Users\12032\Desktop\cdvae-main\cdvae\run.py' exists and readable
```

**Comment by szy120320** [comment]
How should I set the `MODEL_PATH`?

**Comment by szy120320** [comment]
> Excuse me, I'm a first-year graduate student. My programming ability is limited. So I have a question.
> 
> 1. I want to know what the is. I tried many paths, but none of them worked. this is the hint:`MODEL_PATH `
> 
> ```
> hydra.errors.MissingConfigException: Primary config directory not found.
> Check that the config directory '\Users\12032\Desktop\cdvae-main\cdvae\run.py' exists and readable
> ```
I have solved the problem. But I have another problem.

**Comment by szy120320** [comment]
this is error information: 
`AttributeError: 'CrystGNN_Supervise' object has no attribute 'langevin_dynamics'`

I find that the attribute 'langevin_dynamics'  exists in the CDVAE class, not CrysGNN_Supervise. So How do I solve this problem?

**Comment by szy120320** [comment]
@txie-93

**Comment by szy120320** [comment]
when I execute the `recon` command, I ran into a problem: 
```
100%|██████████| 2030/2030 [02:43<00:00, 12.44it/s]
Evaluate model on the reconstruction task.
Traceback (most recent call last):
  File "C:/Users/12032/Desktop/cdvae-main/scripts/evaluate.py", line 281, in <module>
    main(args)
  File "C:/Users/12032/Desktop/cdvae-main/scripts/evaluate.py", line 194, in main
    all_frac_coords_stack, all_atom_types_stack, input_data_batch) = reconstructon(
  File "C:/Users/12032/Desktop/cdvae-main/scripts/evaluate.py", line 38, in reconstructon
    _, _, z = model.encode(batch)
  File "E:\anaconda3\envs\cdvae\lib\site-packages\torch\nn\modules\module.py", line 947, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'CrystGNN_Supervise' object has no attribute 'encode'
batch 0 in 8
```

**Comment by utf** [comment]
Hi @szy120320, did you figure out this problem?

**Comment by szy120320** [comment]
> Hi @szy120320, did you figure out this problem?

I tried, but it didn't work

**Comment by JianZhou711** [comment]
> 

I am probably late and it's already solved, but I worked through it by using the Hydra output from the training instead of prop_models as my model_path which was where I got that error.
