### ISSUE TITLE
training project

### ISSUE THREAD

**Issue by KingDamLiu** [txie-93/cdvae#49]
python cdvae/run.py data=perov expname=perov model.predict_property=True

Traceback (most recent call last):
  File "cdvae/run.py", line 19, in <module>
    from cdvae.common.utils import log_hyperparameters, PROJECT_ROOT
  File "/home/liujinde/CSG/cdvae/cdvae/common/utils.py", line 92, in <module>
    PROJECT_ROOT: Path = Path(get_env("PROJECT_ROOT"))
  File "/home/liujinde/CSG/cdvae/cdvae/common/utils.py", line 22, in get_env
    raise KeyError(
KeyError: 'PROJECT_ROOT not defined and no default value is present!'

**Comment by stargolike** [comment]
i meet this problem,too.
how to take it

**Comment by stargolike** [comment]
hi kingdamliu.
you should view PART Setting up environment variables 
I think this is an environment problem.

**Comment by DanChai22** [comment]
I meet this problem,too. And I have set the .env file
