### ISSUE TITLE
A problem while training model without a property predictor

### ISSUE THREAD

**Issue by 0546trigger** [txie-93/cdvae#50]
Error executing job with overrides: ['data=mp_20', 'expname=mp_20']
Traceback (most recent call last):
  File "/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/site-packages/hydra/_internal/utils.py", line 575, in _locate
    import_module(mod)
  File "/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/gpfs/home/scms/lixiaoyi/cdvae/cdvae/pl_data/datamodule.py", line 15, in <module>
    from cdvae.common.data_utils import get_scaler_from_data_list
  File "/gpfs/home/scms/lixiaoyi/cdvae/cdvae/common/data_utils.py", line 10, in <module>
    from pymatgen.analysis.graphs import StructureGraph
  File "/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/site-packages/pymatgen/analysis/graphs.py", line 22, in <module>
    from monty.os.path import which
ImportError: cannot import name 'which' from 'monty.os.path' (/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/site-packages/monty/os/path.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/home/scms/lixiaoyi/cdvae/cdvae/run.py", line 166, in main
    run(cfg)
  File "/gpfs/home/scms/lixiaoyi/cdvae/cdvae/run.py", line 88, in run
    datamodule: pl.LightningDataModule = hydra.utils.instantiate(
  File "/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 240, in instantiate_node
    target = _resolve_target(node.get(_Keys.TARGET))
  File "/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 104, in _resolve_target
    return _locate(target)
  File "/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/site-packages/hydra/_internal/utils.py", line 577, in _locate
    raise ImportError(
ImportError: Encountered error: `cannot import name 'which' from 'monty.os.path' (/home/scms/lixiaoyi/anaconda3/envs/cdvae/lib/python3.8/site-packages/monty/os/path.py)` when loading module 'cdvae.pl_data.datamodule.CrystDataModule'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by K0R7-K4MP** [comment]
I solved downgrading the monty package
