### ISSUE TITLE
expected scalar type Float but found Doubl

### ISSUE THREAD

**Issue by K0R7-K4MP** [txie-93/cdvae#54]
Got the following error. Anyone has any ideas what could be wrong?

Error executing job with overrides: ['data=carbon', 'expname=carbon', 'model.predict_property=True']
Traceback (most recent call last):
  File "cdvae/run.py", line 166, in main
    run(cfg)
  File "cdvae/run.py", line 154, in run
    trainer.fit(model=model, datamodule=datamodule)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 460, in fit
    self._run(model)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 758, in _run
    self.dispatch()
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 799, in dispatch
    self.accelerator.start_training(self)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in run_stage
    return self.run_train()
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 844, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in run_sanity_check
    self.run_evaluation()
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 967, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/double.py", line 54, in new_method
    return old_method(
  File "/Users/wiltonkortkamp/Downloads/cdvae-main/cdvae/pl_modules/model.py", line 539, in validation_step
    outputs = self(batch, teacher_forcing=False, training=False)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/double.py", line 54, in new_method
    return old_method(
  File "/Users/wiltonkortkamp/Downloads/cdvae-main/cdvae/pl_modules/model.py", line 312, in forward
    mu, log_var, z = self.encode(batch)
  File "/Users/wiltonkortkamp/Downloads/cdvae-main/cdvae/pl_modules/model.py", line 198, in encode
    hidden = self.encoder(batch)
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/wiltonkortkamp/Downloads/cdvae-main/cdvae/pl_modules/gnn.py", line 354, in forward
    pos = frac_to_cart_coords(
  File "/Users/wiltonkortkamp/Downloads/cdvae-main/cdvae/common/data_utils.py", line 253, in frac_to_cart_coords
    pos = torch.einsum('bi,bij->bj', frac_coords, lattice_nodes)  # cart coords
  File "/Users/wiltonkortkamp/opt/anaconda3/envs/cdvae/lib/python3.8/site-packages/torch/functional.py", line 408, in einsum
    return _VF.einsum(equation, operands)  # type: ignore
RuntimeError: expected scalar type Float but found Double

**Comment by K0R7-K4MP** [comment]
Solved: just replace the precision in the pl_trainer hyperparameters to 32 rather than 64.
